-- =========================================================
-- DATALOAD
-- =========================================================

SET datestyle = 'ISO, DMY';


-- 1. CD 

INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (1, 'CD São Paulo - Unidade 1', '00000000000001', 'Rua das Flores, 101 - São Paulo/SP');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (2, 'CD Rio de Janeiro - Unidade 2', '00000000000002', 'Rua Industrial, 102 - Rio de Janeiro/RJ');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (3, 'CD Belo Horizonte - Unidade 3', '00000000000003', 'Rua Comercial, 103 - Belo Horizonte/MG');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (4, 'CD Curitiba - Unidade 4', '00000000000004', 'Rua dos Andradas, 104 - Curitiba/PR');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (5, 'CD Porto Alegre - Unidade 5', '00000000000005', 'Rua Voluntários, 105 - Porto Alegre/RS');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (6, 'CD Salvador - Unidade 6', '00000000000006', 'Rua Brasil, 106 - Salvador/BA');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (7, 'CD Recife - Unidade 7', '00000000000007', 'Rua Central, 107 - Recife/PE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (8, 'CD Fortaleza - Unidade 8', '00000000000008', 'Rua Norte, 108 - Fortaleza/CE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (9, 'CD Brasília - Unidade 9', '00000000000009', 'Rua Sul, 109 - Brasília/DF');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (10, 'CD Manaus - Unidade 10', '00000000000010', 'Rua das Nações, 110 - Manaus/AM');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (11, 'CD São Paulo - Unidade 11', '00000000000011', 'Rua das Flores, 111 - São Paulo/SP');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (12, 'CD Rio de Janeiro - Unidade 12', '00000000000012', 'Rua Industrial, 112 - Rio de Janeiro/RJ');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (13, 'CD Belo Horizonte - Unidade 13', '00000000000013', 'Rua Comercial, 113 - Belo Horizonte/MG');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (14, 'CD Curitiba - Unidade 14', '00000000000014', 'Rua dos Andradas, 114 - Curitiba/PR');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (15, 'CD Porto Alegre - Unidade 15', '00000000000015', 'Rua Voluntários, 115 - Porto Alegre/RS');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (16, 'CD Salvador - Unidade 16', '00000000000016', 'Rua Brasil, 116 - Salvador/BA');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (17, 'CD Recife - Unidade 17', '00000000000017', 'Rua Central, 117 - Recife/PE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (18, 'CD Fortaleza - Unidade 18', '00000000000018', 'Rua Norte, 118 - Fortaleza/CE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (19, 'CD Brasília - Unidade 19', '00000000000019', 'Rua Sul, 119 - Brasília/DF');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (20, 'CD Manaus - Unidade 20', '00000000000020', 'Rua das Nações, 120 - Manaus/AM');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (21, 'CD São Paulo - Unidade 21', '00000000000021', 'Rua das Flores, 121 - São Paulo/SP');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (22, 'CD Rio de Janeiro - Unidade 22', '00000000000022', 'Rua Industrial, 122 - Rio de Janeiro/RJ');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (23, 'CD Belo Horizonte - Unidade 23', '00000000000023', 'Rua Comercial, 123 - Belo Horizonte/MG');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (24, 'CD Curitiba - Unidade 24', '00000000000024', 'Rua dos Andradas, 124 - Curitiba/PR');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (25, 'CD Porto Alegre - Unidade 25', '00000000000025', 'Rua Voluntários, 125 - Porto Alegre/RS');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (26, 'CD Salvador - Unidade 26', '00000000000026', 'Rua Brasil, 126 - Salvador/BA');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (27, 'CD Recife - Unidade 27', '00000000000027', 'Rua Central, 127 - Recife/PE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (28, 'CD Fortaleza - Unidade 28', '00000000000028', 'Rua Norte, 128 - Fortaleza/CE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (29, 'CD Brasília - Unidade 29', '00000000000029', 'Rua Sul, 129 - Brasília/DF');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (30, 'CD Manaus - Unidade 30', '00000000000030', 'Rua das Nações, 130 - Manaus/AM');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (31, 'CD São Paulo - Unidade 31', '00000000000031', 'Rua das Flores, 131 - São Paulo/SP');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (32, 'CD Rio de Janeiro - Unidade 32', '00000000000032', 'Rua Industrial, 132 - Rio de Janeiro/RJ');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (33, 'CD Belo Horizonte - Unidade 33', '00000000000033', 'Rua Comercial, 133 - Belo Horizonte/MG');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (34, 'CD Curitiba - Unidade 34', '00000000000034', 'Rua dos Andradas, 134 - Curitiba/PR');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (35, 'CD Porto Alegre - Unidade 35', '00000000000035', 'Rua Voluntários, 135 - Porto Alegre/RS');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (36, 'CD Salvador - Unidade 36', '00000000000036', 'Rua Brasil, 136 - Salvador/BA');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (37, 'CD Recife - Unidade 37', '00000000000037', 'Rua Central, 137 - Recife/PE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (38, 'CD Fortaleza - Unidade 38', '00000000000038', 'Rua Norte, 138 - Fortaleza/CE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (39, 'CD Brasília - Unidade 39', '00000000000039', 'Rua Sul, 139 - Brasília/DF');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (40, 'CD Manaus - Unidade 40', '00000000000040', 'Rua das Nações, 140 - Manaus/AM');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (41, 'CD São Paulo - Unidade 41', '00000000000041', 'Rua das Flores, 141 - São Paulo/SP');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (42, 'CD Rio de Janeiro - Unidade 42', '00000000000042', 'Rua Industrial, 142 - Rio de Janeiro/RJ');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (43, 'CD Belo Horizonte - Unidade 43', '00000000000043', 'Rua Comercial, 143 - Belo Horizonte/MG');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (44, 'CD Curitiba - Unidade 44', '00000000000044', 'Rua dos Andradas, 144 - Curitiba/PR');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (45, 'CD Porto Alegre - Unidade 45', '00000000000045', 'Rua Voluntários, 145 - Porto Alegre/RS');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (46, 'CD Salvador - Unidade 46', '00000000000046', 'Rua Brasil, 146 - Salvador/BA');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (47, 'CD Recife - Unidade 47', '00000000000047', 'Rua Central, 147 - Recife/PE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (48, 'CD Fortaleza - Unidade 48', '00000000000048', 'Rua Norte, 148 - Fortaleza/CE');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (49, 'CD Brasília - Unidade 49', '00000000000049', 'Rua Sul, 149 - Brasília/DF');
INSERT INTO CD (id_cd, nome, cnpj, endereco) VALUES (50, 'CD Manaus - Unidade 50', '00000000000050', 'Rua das Nações, 150 - Manaus/AM');

-- 2. USUARIO 

INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (1, 'Ana Souza', '00000000001', 'usuario1@logfresh.com', 'Operador de Monitoramento', 'admin', 1);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (2, 'Carlos Lima', '00000000002', 'usuario2@logfresh.com', 'Supervisor de CD', 'gestor', 2);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (3, 'Fernanda Ribeiro', '00000000003', 'usuario3@logfresh.com', 'Gerente de Operações', 'operador', 3);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (4, 'João Almeida', '00000000004', 'usuario4@logfresh.com', 'Gestor de Qualidade', 'admin', 4);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (5, 'Mariana Nunes', '00000000005', 'usuario5@logfresh.com', 'Administrador de Sistema', 'gestor', 5);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (6, 'Rafael Dias', '00000000006', 'usuario6@logfresh.com', 'Operador de Monitoramento', 'operador', 6);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (7, 'Beatriz Costa', '00000000007', 'usuario7@logfresh.com', 'Supervisor de CD', 'admin', 7);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (8, 'Eduardo Pereira', '00000000008', 'usuario8@logfresh.com', 'Gerente de Operações', 'gestor', 8);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (9, 'Camila Santos', '00000000009', 'usuario9@logfresh.com', 'Gestor de Qualidade', 'operador', 9);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (10, 'Lucas Oliveira', '00000000010', 'usuario10@logfresh.com', 'Administrador de Sistema', 'admin', 10);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (11, 'Patrícia Barbosa', '00000000011', 'usuario11@logfresh.com', 'Operador de Monitoramento', 'gestor', 11);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (12, 'Rodrigo Cardoso', '00000000012', 'usuario12@logfresh.com', 'Supervisor de CD', 'operador', 12);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (13, 'Juliana Teixeira', '00000000013', 'usuario13@logfresh.com', 'Gerente de Operações', 'admin', 13);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (14, 'Marcos Rocha', '00000000014', 'usuario14@logfresh.com', 'Gestor de Qualidade', 'gestor', 14);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (15, 'Larissa Martins', '00000000015', 'usuario15@logfresh.com', 'Administrador de Sistema', 'operador', 15);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (16, 'Gustavo Souza', '00000000016', 'usuario16@logfresh.com', 'Operador de Monitoramento', 'admin', 16);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (17, 'Vanessa Lima', '00000000017', 'usuario17@logfresh.com', 'Supervisor de CD', 'gestor', 17);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (18, 'Thiago Ribeiro', '00000000018', 'usuario18@logfresh.com', 'Gerente de Operações', 'operador', 18);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (19, 'Renata Almeida', '00000000019', 'usuario19@logfresh.com', 'Gestor de Qualidade', 'admin', 19);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (20, 'Bruno Nunes', '00000000020', 'usuario20@logfresh.com', 'Administrador de Sistema', 'gestor', 20);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (21, 'Ana Dias', '00000000021', 'usuario21@logfresh.com', 'Operador de Monitoramento', 'operador', 21);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (22, 'Carlos Costa', '00000000022', 'usuario22@logfresh.com', 'Supervisor de CD', 'admin', 22);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (23, 'Fernanda Pereira', '00000000023', 'usuario23@logfresh.com', 'Gerente de Operações', 'gestor', 23);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (24, 'João Santos', '00000000024', 'usuario24@logfresh.com', 'Gestor de Qualidade', 'operador', 24);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (25, 'Mariana Oliveira', '00000000025', 'usuario25@logfresh.com', 'Administrador de Sistema', 'admin', 25);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (26, 'Rafael Barbosa', '00000000026', 'usuario26@logfresh.com', 'Operador de Monitoramento', 'gestor', 26);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (27, 'Beatriz Cardoso', '00000000027', 'usuario27@logfresh.com', 'Supervisor de CD', 'operador', 27);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (28, 'Eduardo Teixeira', '00000000028', 'usuario28@logfresh.com', 'Gerente de Operações', 'admin', 28);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (29, 'Camila Rocha', '00000000029', 'usuario29@logfresh.com', 'Gestor de Qualidade', 'gestor', 29);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (30, 'Lucas Martins', '00000000030', 'usuario30@logfresh.com', 'Administrador de Sistema', 'operador', 30);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (31, 'Patrícia Souza', '00000000031', 'usuario31@logfresh.com', 'Operador de Monitoramento', 'admin', 31);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (32, 'Rodrigo Lima', '00000000032', 'usuario32@logfresh.com', 'Supervisor de CD', 'gestor', 32);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (33, 'Juliana Ribeiro', '00000000033', 'usuario33@logfresh.com', 'Gerente de Operações', 'operador', 33);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (34, 'Marcos Almeida', '00000000034', 'usuario34@logfresh.com', 'Gestor de Qualidade', 'admin', 34);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (35, 'Larissa Nunes', '00000000035', 'usuario35@logfresh.com', 'Administrador de Sistema', 'gestor', 35);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (36, 'Gustavo Dias', '00000000036', 'usuario36@logfresh.com', 'Operador de Monitoramento', 'operador', 36);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (37, 'Vanessa Costa', '00000000037', 'usuario37@logfresh.com', 'Supervisor de CD', 'admin', 37);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (38, 'Thiago Pereira', '00000000038', 'usuario38@logfresh.com', 'Gerente de Operações', 'gestor', 38);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (39, 'Renata Santos', '00000000039', 'usuario39@logfresh.com', 'Gestor de Qualidade', 'operador', 39);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (40, 'Bruno Oliveira', '00000000040', 'usuario40@logfresh.com', 'Administrador de Sistema', 'admin', 40);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (41, 'Ana Barbosa', '00000000041', 'usuario41@logfresh.com', 'Operador de Monitoramento', 'gestor', 41);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (42, 'Carlos Cardoso', '00000000042', 'usuario42@logfresh.com', 'Supervisor de CD', 'operador', 42);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (43, 'Fernanda Teixeira', '00000000043', 'usuario43@logfresh.com', 'Gerente de Operações', 'admin', 43);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (44, 'João Rocha', '00000000044', 'usuario44@logfresh.com', 'Gestor de Qualidade', 'gestor', 44);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (45, 'Mariana Martins', '00000000045', 'usuario45@logfresh.com', 'Administrador de Sistema', 'operador', 45);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (46, 'Rafael Souza', '00000000046', 'usuario46@logfresh.com', 'Operador de Monitoramento', 'admin', 46);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (47, 'Beatriz Lima', '00000000047', 'usuario47@logfresh.com', 'Supervisor de CD', 'gestor', 47);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (48, 'Eduardo Ribeiro', '00000000048', 'usuario48@logfresh.com', 'Gerente de Operações', 'operador', 48);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (49, 'Camila Almeida', '00000000049', 'usuario49@logfresh.com', 'Gestor de Qualidade', 'admin', 49);
INSERT INTO Usuario (id_usuario, nome, cpf, email, cargo, nivel_acesso, id_cd) VALUES (50, 'Lucas Nunes', '00000000050', 'usuario50@logfresh.com', 'Administrador de Sistema', 'gestor', 50);

-- 3. REFRIGERADOR 

INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (1, 'Câmara Fria - Laticínios 1', 'Setor A - Corredor 1', 2.00, 6.00, 1);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (2, 'Câmara Fria - Carnes 2', 'Setor B - Corredor 2', -18.00, -12.00, 2);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (3, 'Câmara Fria - Hortifruti 3', 'Setor C - Corredor 3', 4.00, 10.00, 3);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (4, 'Freezer Industrial 4', 'Setor D - Corredor 4', -25.00, -18.00, 4);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (5, 'Câmara Fria - Bebidas 5', 'Setor A - Corredor 5', 2.00, 8.00, 5);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (6, 'Câmara Fria - Laticínios 6', 'Setor B - Corredor 6', 2.00, 6.00, 6);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (7, 'Câmara Fria - Carnes 7', 'Setor C - Corredor 1', -18.00, -12.00, 7);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (8, 'Câmara Fria - Hortifruti 8', 'Setor D - Corredor 2', 4.00, 10.00, 8);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (9, 'Freezer Industrial 9', 'Setor A - Corredor 3', -25.00, -18.00, 9);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (10, 'Câmara Fria - Bebidas 10', 'Setor B - Corredor 4', 2.00, 8.00, 10);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (11, 'Câmara Fria - Laticínios 11', 'Setor C - Corredor 5', 2.00, 6.00, 11);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (12, 'Câmara Fria - Carnes 12', 'Setor D - Corredor 6', -18.00, -12.00, 12);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (13, 'Câmara Fria - Hortifruti 13', 'Setor A - Corredor 1', 4.00, 10.00, 13);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (14, 'Freezer Industrial 14', 'Setor B - Corredor 2', -25.00, -18.00, 14);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (15, 'Câmara Fria - Bebidas 15', 'Setor C - Corredor 3', 2.00, 8.00, 15);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (16, 'Câmara Fria - Laticínios 16', 'Setor D - Corredor 4', 2.00, 6.00, 16);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (17, 'Câmara Fria - Carnes 17', 'Setor A - Corredor 5', -18.00, -12.00, 17);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (18, 'Câmara Fria - Hortifruti 18', 'Setor B - Corredor 6', 4.00, 10.00, 18);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (19, 'Freezer Industrial 19', 'Setor C - Corredor 1', -25.00, -18.00, 19);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (20, 'Câmara Fria - Bebidas 20', 'Setor D - Corredor 2', 2.00, 8.00, 20);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (21, 'Câmara Fria - Laticínios 21', 'Setor A - Corredor 3', 2.00, 6.00, 21);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (22, 'Câmara Fria - Carnes 22', 'Setor B - Corredor 4', -18.00, -12.00, 22);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (23, 'Câmara Fria - Hortifruti 23', 'Setor C - Corredor 5', 4.00, 10.00, 23);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (24, 'Freezer Industrial 24', 'Setor D - Corredor 6', -25.00, -18.00, 24);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (25, 'Câmara Fria - Bebidas 25', 'Setor A - Corredor 1', 2.00, 8.00, 25);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (26, 'Câmara Fria - Laticínios 26', 'Setor B - Corredor 2', 2.00, 6.00, 26);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (27, 'Câmara Fria - Carnes 27', 'Setor C - Corredor 3', -18.00, -12.00, 27);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (28, 'Câmara Fria - Hortifruti 28', 'Setor D - Corredor 4', 4.00, 10.00, 28);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (29, 'Freezer Industrial 29', 'Setor A - Corredor 5', -25.00, -18.00, 29);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (30, 'Câmara Fria - Bebidas 30', 'Setor B - Corredor 6', 2.00, 8.00, 30);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (31, 'Câmara Fria - Laticínios 31', 'Setor C - Corredor 1', 2.00, 6.00, 31);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (32, 'Câmara Fria - Carnes 32', 'Setor D - Corredor 2', -18.00, -12.00, 32);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (33, 'Câmara Fria - Hortifruti 33', 'Setor A - Corredor 3', 4.00, 10.00, 33);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (34, 'Freezer Industrial 34', 'Setor B - Corredor 4', -25.00, -18.00, 34);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (35, 'Câmara Fria - Bebidas 35', 'Setor C - Corredor 5', 2.00, 8.00, 35);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (36, 'Câmara Fria - Laticínios 36', 'Setor D - Corredor 6', 2.00, 6.00, 36);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (37, 'Câmara Fria - Carnes 37', 'Setor A - Corredor 1', -18.00, -12.00, 37);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (38, 'Câmara Fria - Hortifruti 38', 'Setor B - Corredor 2', 4.00, 10.00, 38);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (39, 'Freezer Industrial 39', 'Setor C - Corredor 3', -25.00, -18.00, 39);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (40, 'Câmara Fria - Bebidas 40', 'Setor D - Corredor 4', 2.00, 8.00, 40);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (41, 'Câmara Fria - Laticínios 41', 'Setor A - Corredor 5', 2.00, 6.00, 41);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (42, 'Câmara Fria - Carnes 42', 'Setor B - Corredor 6', -18.00, -12.00, 42);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (43, 'Câmara Fria - Hortifruti 43', 'Setor C - Corredor 1', 4.00, 10.00, 43);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (44, 'Freezer Industrial 44', 'Setor D - Corredor 2', -25.00, -18.00, 44);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (45, 'Câmara Fria - Bebidas 45', 'Setor A - Corredor 3', 2.00, 8.00, 45);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (46, 'Câmara Fria - Laticínios 46', 'Setor B - Corredor 4', 2.00, 6.00, 46);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (47, 'Câmara Fria - Carnes 47', 'Setor C - Corredor 5', -18.00, -12.00, 47);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (48, 'Câmara Fria - Hortifruti 48', 'Setor D - Corredor 6', 4.00, 10.00, 48);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (49, 'Freezer Industrial 49', 'Setor A - Corredor 1', -25.00, -18.00, 49);
INSERT INTO Refrigerador (id_refrigerador, nome, localizacao, temperatura_min, temperatura_max, id_cd) VALUES (50, 'Câmara Fria - Bebidas 50', 'Setor B - Corredor 2', 2.00, 8.00, 50);

-- 4. PRODUTO 

INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (1, 'Leite Integral 1L - Lote 1', 'Laticínios', 4.00, CURRENT_DATE + 10, 1);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (2, 'Queijo Mussarela - Lote 2', 'Carnes', -15.00, CURRENT_DATE + 11, 2);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (3, 'Iogurte Natural - Lote 3', 'Hortifruti', 6.00, CURRENT_DATE + 12, 3);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (4, 'Contra Filé Bovino - Lote 4', 'Sobremesas', -18.00, CURRENT_DATE + 13, 4);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (5, 'Frango Congelado - Lote 5', 'Bebidas', 5.00, CURRENT_DATE + 14, 5);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (6, 'Alface Crespa - Lote 6', 'Laticínios', 4.00, CURRENT_DATE + 15, 6);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (7, 'Morango Fresco - Lote 7', 'Carnes', -15.00, CURRENT_DATE + 16, 7);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (8, 'Sorvete Napolitano - Lote 8', 'Hortifruti', 6.00, CURRENT_DATE + 17, 8);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (9, 'Polpa de Fruta - Lote 9', 'Sobremesas', -18.00, CURRENT_DATE + 18, 9);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (10, 'Suco de Laranja - Lote 10', 'Bebidas', 5.00, CURRENT_DATE + 19, 10);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (11, 'Manteiga - Lote 11', 'Laticínios', 4.00, CURRENT_DATE + 20, 11);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (12, 'Presunto Fatiado - Lote 12', 'Carnes', -15.00, CURRENT_DATE + 21, 12);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (13, 'Linguiça Congelada - Lote 13', 'Hortifruti', 6.00, CURRENT_DATE + 22, 13);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (14, 'Brócolis - Lote 14', 'Sobremesas', -18.00, CURRENT_DATE + 23, 14);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (15, 'Uva Verde - Lote 15', 'Bebidas', 5.00, CURRENT_DATE + 24, 15);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (16, 'Leite Integral 1L - Lote 16', 'Laticínios', 4.00, CURRENT_DATE + 25, 16);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (17, 'Queijo Mussarela - Lote 17', 'Carnes', -15.00, CURRENT_DATE + 26, 17);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (18, 'Iogurte Natural - Lote 18', 'Hortifruti', 6.00, CURRENT_DATE + 27, 18);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (19, 'Contra Filé Bovino - Lote 19', 'Sobremesas', -18.00, CURRENT_DATE + 28, 19);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (20, 'Frango Congelado - Lote 20', 'Bebidas', 5.00, CURRENT_DATE + 29, 20);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (21, 'Alface Crespa - Lote 21', 'Laticínios', 4.00, CURRENT_DATE + 30, 21);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (22, 'Morango Fresco - Lote 22', 'Carnes', -15.00, CURRENT_DATE + 31, 22);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (23, 'Sorvete Napolitano - Lote 23', 'Hortifruti', 6.00, CURRENT_DATE + 32, 23);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (24, 'Polpa de Fruta - Lote 24', 'Sobremesas', -18.00, CURRENT_DATE + 33, 24);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (25, 'Suco de Laranja - Lote 25', 'Bebidas', 5.00, CURRENT_DATE + 34, 25);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (26, 'Manteiga - Lote 26', 'Laticínios', 4.00, CURRENT_DATE + 35, 26);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (27, 'Presunto Fatiado - Lote 27', 'Carnes', -15.00, CURRENT_DATE + 36, 27);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (28, 'Linguiça Congelada - Lote 28', 'Hortifruti', 6.00, CURRENT_DATE + 37, 28);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (29, 'Brócolis - Lote 29', 'Sobremesas', -18.00, CURRENT_DATE + 38, 29);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (30, 'Uva Verde - Lote 30', 'Bebidas', 5.00, CURRENT_DATE + 39, 30);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (31, 'Leite Integral 1L - Lote 31', 'Laticínios', 4.00, CURRENT_DATE + 40, 31);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (32, 'Queijo Mussarela - Lote 32', 'Carnes', -15.00, CURRENT_DATE + 41, 32);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (33, 'Iogurte Natural - Lote 33', 'Hortifruti', 6.00, CURRENT_DATE + 42, 33);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (34, 'Contra Filé Bovino - Lote 34', 'Sobremesas', -18.00, CURRENT_DATE + 43, 34);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (35, 'Frango Congelado - Lote 35', 'Bebidas', 5.00, CURRENT_DATE + 44, 35);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (36, 'Alface Crespa - Lote 36', 'Laticínios', 4.00, CURRENT_DATE + 45, 36);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (37, 'Morango Fresco - Lote 37', 'Carnes', -15.00, CURRENT_DATE + 46, 37);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (38, 'Sorvete Napolitano - Lote 38', 'Hortifruti', 6.00, CURRENT_DATE + 47, 38);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (39, 'Polpa de Fruta - Lote 39', 'Sobremesas', -18.00, CURRENT_DATE + 48, 39);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (40, 'Suco de Laranja - Lote 40', 'Bebidas', 5.00, CURRENT_DATE + 49, 40);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (41, 'Manteiga - Lote 41', 'Laticínios', 4.00, CURRENT_DATE + 50, 41);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (42, 'Presunto Fatiado - Lote 42', 'Carnes', -15.00, CURRENT_DATE + 51, 42);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (43, 'Linguiça Congelada - Lote 43', 'Hortifruti', 6.00, CURRENT_DATE + 52, 43);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (44, 'Brócolis - Lote 44', 'Sobremesas', -18.00, CURRENT_DATE + 53, 44);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (45, 'Uva Verde - Lote 45', 'Bebidas', 5.00, CURRENT_DATE + 54, 45);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (46, 'Leite Integral 1L - Lote 46', 'Laticínios', 4.00, CURRENT_DATE + 55, 46);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (47, 'Queijo Mussarela - Lote 47', 'Carnes', -15.00, CURRENT_DATE + 56, 47);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (48, 'Iogurte Natural - Lote 48', 'Hortifruti', 6.00, CURRENT_DATE + 57, 48);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (49, 'Contra Filé Bovino - Lote 49', 'Sobremesas', -18.00, CURRENT_DATE + 58, 49);
INSERT INTO Produto (id_produto, nome, categoria, temperatura_ideal, validade, id_refrigerador) VALUES (50, 'Frango Congelado - Lote 50', 'Bebidas', 5.00, CURRENT_DATE + 59, 50);

-- 5. TERMOMETRO 

INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (1, 'Sensor DHT-2200', 'ativo', 1);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (2, 'Sensor TempLog X3', 'ativo', 2);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (3, 'Sensor TermoSense Pro', 'ativo', 3);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (4, 'Sensor IoT-Cold', 'inativo', 4);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (5, 'Sensor ThermoGuard', 'manutencao', 5);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (6, 'Sensor DHT-2200', 'defeito', 6);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (7, 'Sensor TempLog X3', 'ativo', 7);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (8, 'Sensor TermoSense Pro', 'ativo', 8);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (9, 'Sensor IoT-Cold', 'ativo', 9);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (10, 'Sensor ThermoGuard', 'inativo', 10);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (11, 'Sensor DHT-2200', 'manutencao', 11);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (12, 'Sensor TempLog X3', 'defeito', 12);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (13, 'Sensor TermoSense Pro', 'ativo', 13);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (14, 'Sensor IoT-Cold', 'ativo', 14);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (15, 'Sensor ThermoGuard', 'ativo', 15);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (16, 'Sensor DHT-2200', 'inativo', 16);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (17, 'Sensor TempLog X3', 'manutencao', 17);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (18, 'Sensor TermoSense Pro', 'defeito', 18);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (19, 'Sensor IoT-Cold', 'ativo', 19);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (20, 'Sensor ThermoGuard', 'ativo', 20);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (21, 'Sensor DHT-2200', 'ativo', 21);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (22, 'Sensor TempLog X3', 'inativo', 22);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (23, 'Sensor TermoSense Pro', 'manutencao', 23);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (24, 'Sensor IoT-Cold', 'defeito', 24);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (25, 'Sensor ThermoGuard', 'ativo', 25);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (26, 'Sensor DHT-2200', 'ativo', 26);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (27, 'Sensor TempLog X3', 'ativo', 27);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (28, 'Sensor TermoSense Pro', 'inativo', 28);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (29, 'Sensor IoT-Cold', 'manutencao', 29);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (30, 'Sensor ThermoGuard', 'defeito', 30);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (31, 'Sensor DHT-2200', 'ativo', 31);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (32, 'Sensor TempLog X3', 'ativo', 32);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (33, 'Sensor TermoSense Pro', 'ativo', 33);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (34, 'Sensor IoT-Cold', 'inativo', 34);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (35, 'Sensor ThermoGuard', 'manutencao', 35);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (36, 'Sensor DHT-2200', 'defeito', 36);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (37, 'Sensor TempLog X3', 'ativo', 37);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (38, 'Sensor TermoSense Pro', 'ativo', 38);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (39, 'Sensor IoT-Cold', 'ativo', 39);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (40, 'Sensor ThermoGuard', 'inativo', 40);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (41, 'Sensor DHT-2200', 'manutencao', 41);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (42, 'Sensor TempLog X3', 'defeito', 42);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (43, 'Sensor TermoSense Pro', 'ativo', 43);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (44, 'Sensor IoT-Cold', 'ativo', 44);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (45, 'Sensor ThermoGuard', 'ativo', 45);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (46, 'Sensor DHT-2200', 'inativo', 46);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (47, 'Sensor TempLog X3', 'manutencao', 47);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (48, 'Sensor TermoSense Pro', 'defeito', 48);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (49, 'Sensor IoT-Cold', 'ativo', 49);
INSERT INTO Termometro (id_termometro, modelo, status, id_refrigerador) VALUES (50, 'Sensor ThermoGuard', 'ativo', 50);

-- 6. LEITURATEMPERATURA 

INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (1, 5.80, CURRENT_DATE - 0, 1);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (2, -14.70, CURRENT_DATE - 1, 2);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (3, 5.80, CURRENT_DATE - 2, 3);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (4, -22.70, CURRENT_DATE - 3, 4);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (5, 7.10, CURRENT_DATE - 4, 5);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (6, 4.60, CURRENT_DATE - 5, 6);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (7, -15.90, CURRENT_DATE - 6, 7);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (8, 4.60, CURRENT_DATE - 7, 8);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (9, -17.60, CURRENT_DATE - 8, 9);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (10, 5.90, CURRENT_DATE - 9, 10);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (11, 3.40, CURRENT_DATE - 10, 11);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (12, -17.10, CURRENT_DATE - 11, 12);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (13, 9.70, CURRENT_DATE - 12, 13);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (14, -18.80, CURRENT_DATE - 13, 14);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (15, 4.70, CURRENT_DATE - 14, 15);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (16, 2.20, CURRENT_DATE - 15, 16);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (17, -12.00, CURRENT_DATE - 16, 17);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (18, 8.50, CURRENT_DATE - 17, 18);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (19, -20.00, CURRENT_DATE - 18, 19);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (20, 3.50, CURRENT_DATE - 19, 20);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (21, 1.00, CURRENT_DATE - 20, 21);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (22, -13.20, CURRENT_DATE - 21, 22);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (23, 7.30, CURRENT_DATE - 22, 23);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (24, -21.20, CURRENT_DATE - 23, 24);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (25, 2.30, CURRENT_DATE - 24, 25);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (26, 6.10, CURRENT_DATE - 25, 26);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (27, -14.40, CURRENT_DATE - 26, 27);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (28, 6.10, CURRENT_DATE - 27, 28);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (29, -22.40, CURRENT_DATE - 28, 29);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (30, 7.40, CURRENT_DATE - 29, 30);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (31, 4.90, CURRENT_DATE - 0, 31);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (32, -15.60, CURRENT_DATE - 1, 32);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (33, 4.90, CURRENT_DATE - 2, 33);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (34, -17.30, CURRENT_DATE - 3, 34);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (35, 6.20, CURRENT_DATE - 4, 35);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (36, 3.70, CURRENT_DATE - 5, 36);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (37, -16.80, CURRENT_DATE - 6, 37);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (38, 10.00, CURRENT_DATE - 7, 38);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (39, -18.50, CURRENT_DATE - 8, 39);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (40, 5.00, CURRENT_DATE - 9, 40);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (41, 2.50, CURRENT_DATE - 10, 41);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (42, -18.00, CURRENT_DATE - 11, 42);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (43, 8.80, CURRENT_DATE - 12, 43);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (44, -19.70, CURRENT_DATE - 13, 44);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (45, 3.80, CURRENT_DATE - 14, 45);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (46, 1.30, CURRENT_DATE - 15, 46);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (47, -12.90, CURRENT_DATE - 16, 47);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (48, 7.60, CURRENT_DATE - 17, 48);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (49, -20.90, CURRENT_DATE - 18, 49);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data, id_termometro) VALUES (50, 2.60, CURRENT_DATE - 19, 50);

-- 7. ALERTA

INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (1, 'pendente', 5, CURRENT_TIMESTAMP - INTERVAL '0 hours', 'temperatura_alta', 'baixo', 'email', 'Alerta automático gerado para leitura #1', CURRENT_DATE - 0, 1, 1);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (2, 'em_andamento', 10, CURRENT_TIMESTAMP - INTERVAL '1 hours', 'temperatura_baixa', 'medio', 'sms', 'Alerta automático gerado para leitura #2', CURRENT_DATE - 1, 2, 2);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (3, 'resolvido', 15, CURRENT_TIMESTAMP - INTERVAL '2 hours', 'sensor_defeito', 'alto', 'app', 'Alerta automático gerado para leitura #3', NULL, 3, 3);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (4, 'ignorado', 20, CURRENT_TIMESTAMP - INTERVAL '3 hours', 'porta_aberta', 'critico', 'painel', 'Alerta automático gerado para leitura #4', CURRENT_DATE - 3, 4, 4);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (5, 'pendente', 25, CURRENT_TIMESTAMP - INTERVAL '4 hours', 'falha_energia', 'baixo', 'email', 'Alerta automático gerado para leitura #5', CURRENT_DATE - 4, 5, 5);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (6, 'em_andamento', 30, CURRENT_TIMESTAMP - INTERVAL '5 hours', 'temperatura_alta', 'medio', 'sms', 'Alerta automático gerado para leitura #6', NULL, 6, 6);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (7, 'resolvido', NULL, CURRENT_TIMESTAMP - INTERVAL '6 hours', 'temperatura_baixa', 'alto', 'app', 'Alerta automático gerado para leitura #7', CURRENT_DATE - 6, 7, 7);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (8, 'ignorado', 40, CURRENT_TIMESTAMP - INTERVAL '7 hours', 'sensor_defeito', 'critico', 'painel', 'Alerta automático gerado para leitura #8', CURRENT_DATE - 7, 8, 8);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (9, 'pendente', 45, CURRENT_TIMESTAMP - INTERVAL '8 hours', 'porta_aberta', 'baixo', 'email', 'Alerta automático gerado para leitura #9', NULL, 9, 9);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (10, 'em_andamento', 50, CURRENT_TIMESTAMP - INTERVAL '9 hours', 'falha_energia', 'medio', 'sms', 'Alerta automático gerado para leitura #10', CURRENT_DATE - 9, 10, 10);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (11, 'resolvido', 55, CURRENT_TIMESTAMP - INTERVAL '10 hours', 'temperatura_alta', 'alto', 'app', 'Alerta automático gerado para leitura #11', CURRENT_DATE - 0, 11, 11);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (12, 'ignorado', 60, CURRENT_TIMESTAMP - INTERVAL '11 hours', 'temperatura_baixa', 'critico', 'painel', 'Alerta automático gerado para leitura #12', NULL, 12, 12);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (13, 'pendente', 65, CURRENT_TIMESTAMP - INTERVAL '12 hours', 'sensor_defeito', 'baixo', 'email', 'Alerta automático gerado para leitura #13', CURRENT_DATE - 2, 13, 13);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (14, 'em_andamento', NULL, CURRENT_TIMESTAMP - INTERVAL '13 hours', 'porta_aberta', 'medio', 'sms', 'Alerta automático gerado para leitura #14', CURRENT_DATE - 3, 14, 14);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (15, 'resolvido', 75, CURRENT_TIMESTAMP - INTERVAL '14 hours', 'falha_energia', 'alto', 'app', 'Alerta automático gerado para leitura #15', NULL, 15, 15);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (16, 'ignorado', 80, CURRENT_TIMESTAMP - INTERVAL '15 hours', 'temperatura_alta', 'critico', 'painel', 'Alerta automático gerado para leitura #16', CURRENT_DATE - 5, 16, 16);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (17, 'pendente', 85, CURRENT_TIMESTAMP - INTERVAL '16 hours', 'temperatura_baixa', 'baixo', 'email', 'Alerta automático gerado para leitura #17', CURRENT_DATE - 6, 17, 17);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (18, 'em_andamento', 90, CURRENT_TIMESTAMP - INTERVAL '17 hours', 'sensor_defeito', 'medio', 'sms', 'Alerta automático gerado para leitura #18', NULL, 18, 18);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (19, 'resolvido', 95, CURRENT_TIMESTAMP - INTERVAL '18 hours', 'porta_aberta', 'alto', 'app', 'Alerta automático gerado para leitura #19', CURRENT_DATE - 8, 19, 19);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (20, 'ignorado', 100, CURRENT_TIMESTAMP - INTERVAL '19 hours', 'falha_energia', 'critico', 'painel', 'Alerta automático gerado para leitura #20', CURRENT_DATE - 9, 20, 20);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (21, 'pendente', NULL, CURRENT_TIMESTAMP - INTERVAL '20 hours', 'temperatura_alta', 'baixo', 'email', 'Alerta automático gerado para leitura #21', NULL, 21, 21);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (22, 'em_andamento', 110, CURRENT_TIMESTAMP - INTERVAL '21 hours', 'temperatura_baixa', 'medio', 'sms', 'Alerta automático gerado para leitura #22', CURRENT_DATE - 1, 22, 22);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (23, 'resolvido', 115, CURRENT_TIMESTAMP - INTERVAL '22 hours', 'sensor_defeito', 'alto', 'app', 'Alerta automático gerado para leitura #23', CURRENT_DATE - 2, 23, 23);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (24, 'ignorado', 120, CURRENT_TIMESTAMP - INTERVAL '23 hours', 'porta_aberta', 'critico', 'painel', 'Alerta automático gerado para leitura #24', NULL, 24, 24);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (25, 'pendente', 125, CURRENT_TIMESTAMP - INTERVAL '24 hours', 'falha_energia', 'baixo', 'email', 'Alerta automático gerado para leitura #25', CURRENT_DATE - 4, 25, 25);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (26, 'em_andamento', 130, CURRENT_TIMESTAMP - INTERVAL '25 hours', 'temperatura_alta', 'medio', 'sms', 'Alerta automático gerado para leitura #26', CURRENT_DATE - 5, 26, 26);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (27, 'resolvido', 135, CURRENT_TIMESTAMP - INTERVAL '26 hours', 'temperatura_baixa', 'alto', 'app', 'Alerta automático gerado para leitura #27', NULL, 27, 27);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (28, 'ignorado', NULL, CURRENT_TIMESTAMP - INTERVAL '27 hours', 'sensor_defeito', 'critico', 'painel', 'Alerta automático gerado para leitura #28', CURRENT_DATE - 7, 28, 28);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (29, 'pendente', 145, CURRENT_TIMESTAMP - INTERVAL '28 hours', 'porta_aberta', 'baixo', 'email', 'Alerta automático gerado para leitura #29', CURRENT_DATE - 8, 29, 29);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (30, 'em_andamento', 150, CURRENT_TIMESTAMP - INTERVAL '29 hours', 'falha_energia', 'medio', 'sms', 'Alerta automático gerado para leitura #30', NULL, 30, 30);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (31, 'resolvido', 155, CURRENT_TIMESTAMP - INTERVAL '30 hours', 'temperatura_alta', 'alto', 'app', 'Alerta automático gerado para leitura #31', CURRENT_DATE - 0, 31, 31);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (32, 'ignorado', 160, CURRENT_TIMESTAMP - INTERVAL '31 hours', 'temperatura_baixa', 'critico', 'painel', 'Alerta automático gerado para leitura #32', CURRENT_DATE - 1, 32, 32);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (33, 'pendente', 165, CURRENT_TIMESTAMP - INTERVAL '32 hours', 'sensor_defeito', 'baixo', 'email', 'Alerta automático gerado para leitura #33', NULL, 33, 33);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (34, 'em_andamento', 170, CURRENT_TIMESTAMP - INTERVAL '33 hours', 'porta_aberta', 'medio', 'sms', 'Alerta automático gerado para leitura #34', CURRENT_DATE - 3, 34, 34);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (35, 'resolvido', NULL, CURRENT_TIMESTAMP - INTERVAL '34 hours', 'falha_energia', 'alto', 'app', 'Alerta automático gerado para leitura #35', CURRENT_DATE - 4, 35, 35);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (36, 'ignorado', 0, CURRENT_TIMESTAMP - INTERVAL '35 hours', 'temperatura_alta', 'critico', 'painel', 'Alerta automático gerado para leitura #36', NULL, 36, 36);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (37, 'pendente', 5, CURRENT_TIMESTAMP - INTERVAL '36 hours', 'temperatura_baixa', 'baixo', 'email', 'Alerta automático gerado para leitura #37', CURRENT_DATE - 6, 37, 37);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (38, 'em_andamento', 10, CURRENT_TIMESTAMP - INTERVAL '37 hours', 'sensor_defeito', 'medio', 'sms', 'Alerta automático gerado para leitura #38', CURRENT_DATE - 7, 38, 38);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (39, 'resolvido', 15, CURRENT_TIMESTAMP - INTERVAL '38 hours', 'porta_aberta', 'alto', 'app', 'Alerta automático gerado para leitura #39', NULL, 39, 39);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (40, 'ignorado', 20, CURRENT_TIMESTAMP - INTERVAL '39 hours', 'falha_energia', 'critico', 'painel', 'Alerta automático gerado para leitura #40', CURRENT_DATE - 9, 40, 40);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (41, 'pendente', 25, CURRENT_TIMESTAMP - INTERVAL '40 hours', 'temperatura_alta', 'baixo', 'email', 'Alerta automático gerado para leitura #41', CURRENT_DATE - 0, 41, 41);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (42, 'em_andamento', NULL, CURRENT_TIMESTAMP - INTERVAL '41 hours', 'temperatura_baixa', 'medio', 'sms', 'Alerta automático gerado para leitura #42', NULL, 42, 42);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (43, 'resolvido', 35, CURRENT_TIMESTAMP - INTERVAL '42 hours', 'sensor_defeito', 'alto', 'app', 'Alerta automático gerado para leitura #43', CURRENT_DATE - 2, 43, 43);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (44, 'ignorado', 40, CURRENT_TIMESTAMP - INTERVAL '43 hours', 'porta_aberta', 'critico', 'painel', 'Alerta automático gerado para leitura #44', CURRENT_DATE - 3, 44, 44);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (45, 'pendente', 45, CURRENT_TIMESTAMP - INTERVAL '44 hours', 'falha_energia', 'baixo', 'email', 'Alerta automático gerado para leitura #45', NULL, 45, 45);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (46, 'em_andamento', 50, CURRENT_TIMESTAMP - INTERVAL '45 hours', 'temperatura_alta', 'medio', 'sms', 'Alerta automático gerado para leitura #46', CURRENT_DATE - 5, 46, 46);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (47, 'resolvido', 55, CURRENT_TIMESTAMP - INTERVAL '46 hours', 'temperatura_baixa', 'alto', 'app', 'Alerta automático gerado para leitura #47', CURRENT_DATE - 6, 47, 47);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (48, 'ignorado', 60, CURRENT_TIMESTAMP - INTERVAL '47 hours', 'sensor_defeito', 'critico', 'painel', 'Alerta automático gerado para leitura #48', NULL, 48, 48);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (49, 'pendente', NULL, CURRENT_TIMESTAMP - INTERVAL '48 hours', 'porta_aberta', 'baixo', 'email', 'Alerta automático gerado para leitura #49', CURRENT_DATE - 8, 49, 49);
INSERT INTO Alerta (id_alerta, status, tempo_sobrevivencia, data_hora, tipo, nivel_gravidade, canal, notificacao, data_envio, id_leitura, id_usuario) VALUES (50, 'em_andamento', 70, CURRENT_TIMESTAMP - INTERVAL '49 hours', 'falha_energia', 'medio', 'sms', 'Alerta automático gerado para leitura #50', CURRENT_DATE - 9, 50, 50);

