-- =========================================================
-- DATALOAD - BANCO DO SKADI
-- =========================================================

SET datestyle = 'ISO, DMY';

-- CD

INSERT INTO CD (id_cd, nome, cnpj) VALUES (1, 'CD São Paulo - Unidade 1', '00000000000001');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (2, 'CD Rio de Janeiro - Unidade 2', '00000000000002');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (3, 'CD Belo Horizonte - Unidade 3', '00000000000003');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (4, 'CD Curitiba - Unidade 4', '00000000000004');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (5, 'CD Porto Alegre - Unidade 5', '00000000000005');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (6, 'CD Salvador - Unidade 6', '00000000000006');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (7, 'CD Recife - Unidade 7', '00000000000007');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (8, 'CD Fortaleza - Unidade 8', '00000000000008');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (9, 'CD Brasília - Unidade 9', '00000000000009');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (10, 'CD Manaus - Unidade 10', '00000000000010');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (11, 'CD São Paulo - Unidade 11', '00000000000011');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (12, 'CD Rio de Janeiro - Unidade 12', '00000000000012');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (13, 'CD Belo Horizonte - Unidade 13', '00000000000013');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (14, 'CD Curitiba - Unidade 14', '00000000000014');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (15, 'CD Porto Alegre - Unidade 15', '00000000000015');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (16, 'CD Salvador - Unidade 16', '00000000000016');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (17, 'CD Recife - Unidade 17', '00000000000017');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (18, 'CD Fortaleza - Unidade 18', '00000000000018');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (19, 'CD Brasília - Unidade 19', '00000000000019');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (20, 'CD Manaus - Unidade 20', '00000000000020');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (21, 'CD São Paulo - Unidade 21', '00000000000021');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (22, 'CD Rio de Janeiro - Unidade 22', '00000000000022');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (23, 'CD Belo Horizonte - Unidade 23', '00000000000023');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (24, 'CD Curitiba - Unidade 24', '00000000000024');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (25, 'CD Porto Alegre - Unidade 25', '00000000000025');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (26, 'CD Salvador - Unidade 26', '00000000000026');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (27, 'CD Recife - Unidade 27', '00000000000027');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (28, 'CD Fortaleza - Unidade 28', '00000000000028');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (29, 'CD Brasília - Unidade 29', '00000000000029');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (30, 'CD Manaus - Unidade 30', '00000000000030');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (31, 'CD São Paulo - Unidade 31', '00000000000031');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (32, 'CD Rio de Janeiro - Unidade 32', '00000000000032');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (33, 'CD Belo Horizonte - Unidade 33', '00000000000033');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (34, 'CD Curitiba - Unidade 34', '00000000000034');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (35, 'CD Porto Alegre - Unidade 35', '00000000000035');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (36, 'CD Salvador - Unidade 36', '00000000000036');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (37, 'CD Recife - Unidade 37', '00000000000037');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (38, 'CD Fortaleza - Unidade 38', '00000000000038');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (39, 'CD Brasília - Unidade 39', '00000000000039');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (40, 'CD Manaus - Unidade 40', '00000000000040');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (41, 'CD São Paulo - Unidade 41', '00000000000041');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (42, 'CD Rio de Janeiro - Unidade 42', '00000000000042');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (43, 'CD Belo Horizonte - Unidade 43', '00000000000043');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (44, 'CD Curitiba - Unidade 44', '00000000000044');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (45, 'CD Porto Alegre - Unidade 45', '00000000000045');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (46, 'CD Salvador - Unidade 46', '00000000000046');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (47, 'CD Recife - Unidade 47', '00000000000047');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (48, 'CD Fortaleza - Unidade 48', '00000000000048');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (49, 'CD Brasília - Unidade 49', '00000000000049');
INSERT INTO CD (id_cd, nome, cnpj) VALUES (50, 'CD Manaus - Unidade 50', '00000000000050');

-- ENDERECO

INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (1, 1, 'Rua das Flores', 101, 'Zona Industrial', 'São Paulo', 'SP', '10000137');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (2, 2, 'Rua Industrial', 102, 'Distrito Industrial', 'Rio de Janeiro', 'RJ', '10000274');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (3, 3, 'Rua Comercial', 103, 'Setor Logístico', 'Belo Horizonte', 'MG', '10000411');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (4, 4, 'Rua dos Andradas', 104, 'Vila Operária', 'Curitiba', 'PR', '10000548');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (5, 5, 'Rua Voluntários', 105, 'Centro', 'Porto Alegre', 'RS', '10000685');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (6, 6, 'Rua Brasil', 106, 'Zona Industrial', 'Salvador', 'BA', '10000822');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (7, 7, 'Rua Central', 107, 'Distrito Industrial', 'Recife', 'PE', '10000959');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (8, 8, 'Rua Norte', 108, 'Setor Logístico', 'Fortaleza', 'CE', '10001096');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (9, 9, 'Rua Sul', 109, 'Vila Operária', 'Brasília', 'DF', '10001233');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (10, 10, 'Rua das Nações', 110, 'Centro', 'Manaus', 'AM', '10001370');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (11, 11, 'Rua das Flores', 111, 'Zona Industrial', 'São Paulo', 'SP', '10001507');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (12, 12, 'Rua Industrial', 112, 'Distrito Industrial', 'Rio de Janeiro', 'RJ', '10001644');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (13, 13, 'Rua Comercial', 113, 'Setor Logístico', 'Belo Horizonte', 'MG', '10001781');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (14, 14, 'Rua dos Andradas', 114, 'Vila Operária', 'Curitiba', 'PR', '10001918');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (15, 15, 'Rua Voluntários', 115, 'Centro', 'Porto Alegre', 'RS', '10002055');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (16, 16, 'Rua Brasil', 116, 'Zona Industrial', 'Salvador', 'BA', '10002192');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (17, 17, 'Rua Central', 117, 'Distrito Industrial', 'Recife', 'PE', '10002329');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (18, 18, 'Rua Norte', 118, 'Setor Logístico', 'Fortaleza', 'CE', '10002466');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (19, 19, 'Rua Sul', 119, 'Vila Operária', 'Brasília', 'DF', '10002603');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (20, 20, 'Rua das Nações', 120, 'Centro', 'Manaus', 'AM', '10002740');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (21, 21, 'Rua das Flores', 121, 'Zona Industrial', 'São Paulo', 'SP', '10002877');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (22, 22, 'Rua Industrial', 122, 'Distrito Industrial', 'Rio de Janeiro', 'RJ', '10003014');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (23, 23, 'Rua Comercial', 123, 'Setor Logístico', 'Belo Horizonte', 'MG', '10003151');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (24, 24, 'Rua dos Andradas', 124, 'Vila Operária', 'Curitiba', 'PR', '10003288');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (25, 25, 'Rua Voluntários', 125, 'Centro', 'Porto Alegre', 'RS', '10003425');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (26, 26, 'Rua Brasil', 126, 'Zona Industrial', 'Salvador', 'BA', '10003562');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (27, 27, 'Rua Central', 127, 'Distrito Industrial', 'Recife', 'PE', '10003699');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (28, 28, 'Rua Norte', 128, 'Setor Logístico', 'Fortaleza', 'CE', '10003836');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (29, 29, 'Rua Sul', 129, 'Vila Operária', 'Brasília', 'DF', '10003973');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (30, 30, 'Rua das Nações', 130, 'Centro', 'Manaus', 'AM', '10004110');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (31, 31, 'Rua das Flores', 131, 'Zona Industrial', 'São Paulo', 'SP', '10004247');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (32, 32, 'Rua Industrial', 132, 'Distrito Industrial', 'Rio de Janeiro', 'RJ', '10004384');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (33, 33, 'Rua Comercial', 133, 'Setor Logístico', 'Belo Horizonte', 'MG', '10004521');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (34, 34, 'Rua dos Andradas', 134, 'Vila Operária', 'Curitiba', 'PR', '10004658');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (35, 35, 'Rua Voluntários', 135, 'Centro', 'Porto Alegre', 'RS', '10004795');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (36, 36, 'Rua Brasil', 136, 'Zona Industrial', 'Salvador', 'BA', '10004932');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (37, 37, 'Rua Central', 137, 'Distrito Industrial', 'Recife', 'PE', '10005069');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (38, 38, 'Rua Norte', 138, 'Setor Logístico', 'Fortaleza', 'CE', '10005206');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (39, 39, 'Rua Sul', 139, 'Vila Operária', 'Brasília', 'DF', '10005343');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (40, 40, 'Rua das Nações', 140, 'Centro', 'Manaus', 'AM', '10005480');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (41, 41, 'Rua das Flores', 141, 'Zona Industrial', 'São Paulo', 'SP', '10005617');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (42, 42, 'Rua Industrial', 142, 'Distrito Industrial', 'Rio de Janeiro', 'RJ', '10005754');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (43, 43, 'Rua Comercial', 143, 'Setor Logístico', 'Belo Horizonte', 'MG', '10005891');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (44, 44, 'Rua dos Andradas', 144, 'Vila Operária', 'Curitiba', 'PR', '10006028');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (45, 45, 'Rua Voluntários', 145, 'Centro', 'Porto Alegre', 'RS', '10006165');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (46, 46, 'Rua Brasil', 146, 'Zona Industrial', 'Salvador', 'BA', '10006302');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (47, 47, 'Rua Central', 147, 'Distrito Industrial', 'Recife', 'PE', '10006439');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (48, 48, 'Rua Norte', 148, 'Setor Logístico', 'Fortaleza', 'CE', '10006576');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (49, 49, 'Rua Sul', 149, 'Vila Operária', 'Brasília', 'DF', '10006713');
INSERT INTO Endereco (id_endereco, id_cd, rua, numero, bairro, cidade, estado, cep) VALUES (50, 50, 'Rua das Nações', 150, 'Centro', 'Manaus', 'AM', '10006850');

-- USUARIO 

INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (1, 'usuario1', NULL, 'Ana Souza', '00000000001', 'usuario1@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 1);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (2, 'usuario2', NULL, 'Carlos Lima', '00000000002', 'usuario2@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 2);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (3, 'usuario3', NULL, 'Fernanda Ribeiro', '00000000003', 'usuario3@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 3);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (4, 'usuario4', NULL, 'João Almeida', '00000000004', 'usuario4@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 4);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (5, 'usuario5', NULL, 'Mariana Nunes', '00000000005', 'usuario5@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 5);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (6, 'usuario6', 5, 'Rafael Dias', '00000000006', 'usuario6@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 6);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (7, 'usuario7', 5, 'Beatriz Costa', '00000000007', 'usuario7@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 7);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (8, 'usuario8', 5, 'Eduardo Pereira', '00000000008', 'usuario8@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 8);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (9, 'usuario9', 5, 'Camila Santos', '00000000009', 'usuario9@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 9);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (10, 'usuario10', NULL, 'Lucas Oliveira', '00000000010', 'usuario10@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 10);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (11, 'usuario11', 10, 'Patrícia Barbosa', '00000000011', 'usuario11@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 11);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (12, 'usuario12', 10, 'Rodrigo Cardoso', '00000000012', 'usuario12@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 12);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (13, 'usuario13', 10, 'Juliana Teixeira', '00000000013', 'usuario13@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 13);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (14, 'usuario14', 10, 'Marcos Rocha', '00000000014', 'usuario14@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 14);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (15, 'usuario15', NULL, 'Larissa Martins', '00000000015', 'usuario15@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 15);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (16, 'usuario16', 15, 'Gustavo Souza', '00000000016', 'usuario16@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 16);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (17, 'usuario17', 15, 'Vanessa Lima', '00000000017', 'usuario17@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 17);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (18, 'usuario18', 15, 'Thiago Ribeiro', '00000000018', 'usuario18@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 18);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (19, 'usuario19', 15, 'Renata Almeida', '00000000019', 'usuario19@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 19);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (20, 'usuario20', NULL, 'Bruno Nunes', '00000000020', 'usuario20@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 20);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (21, 'usuario21', 20, 'Ana Dias', '00000000021', 'usuario21@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 21);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (22, 'usuario22', 20, 'Carlos Costa', '00000000022', 'usuario22@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 22);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (23, 'usuario23', 20, 'Fernanda Pereira', '00000000023', 'usuario23@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 23);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (24, 'usuario24', 20, 'João Santos', '00000000024', 'usuario24@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 24);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (25, 'usuario25', NULL, 'Mariana Oliveira', '00000000025', 'usuario25@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 25);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (26, 'usuario26', 25, 'Rafael Barbosa', '00000000026', 'usuario26@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 26);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (27, 'usuario27', 25, 'Beatriz Cardoso', '00000000027', 'usuario27@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 27);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (28, 'usuario28', 25, 'Eduardo Teixeira', '00000000028', 'usuario28@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 28);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (29, 'usuario29', 25, 'Camila Rocha', '00000000029', 'usuario29@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 29);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (30, 'usuario30', NULL, 'Lucas Martins', '00000000030', 'usuario30@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 30);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (31, 'usuario31', 30, 'Patrícia Souza', '00000000031', 'usuario31@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 31);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (32, 'usuario32', 30, 'Rodrigo Lima', '00000000032', 'usuario32@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 32);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (33, 'usuario33', 30, 'Juliana Ribeiro', '00000000033', 'usuario33@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 33);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (34, 'usuario34', 30, 'Marcos Almeida', '00000000034', 'usuario34@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 34);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (35, 'usuario35', NULL, 'Larissa Nunes', '00000000035', 'usuario35@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 35);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (36, 'usuario36', 35, 'Gustavo Dias', '00000000036', 'usuario36@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 36);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (37, 'usuario37', 35, 'Vanessa Costa', '00000000037', 'usuario37@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 37);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (38, 'usuario38', 35, 'Thiago Pereira', '00000000038', 'usuario38@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 38);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (39, 'usuario39', 35, 'Renata Santos', '00000000039', 'usuario39@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 39);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (40, 'usuario40', NULL, 'Bruno Oliveira', '00000000040', 'usuario40@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 40);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (41, 'usuario41', 40, 'Ana Barbosa', '00000000041', 'usuario41@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 41);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (42, 'usuario42', 40, 'Carlos Cardoso', '00000000042', 'usuario42@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 42);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (43, 'usuario43', 40, 'Fernanda Teixeira', '00000000043', 'usuario43@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 43);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (44, 'usuario44', 40, 'João Rocha', '00000000044', 'usuario44@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 44);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (45, 'usuario45', NULL, 'Mariana Martins', '00000000045', 'usuario45@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 45);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (46, 'usuario46', 45, 'Rafael Souza', '00000000046', 'usuario46@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Operador de Monitoramento', 'operador', 46);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (47, 'usuario47', 45, 'Beatriz Lima', '00000000047', 'usuario47@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Supervisor de CD', 'gestor', 47);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (48, 'usuario48', 45, 'Eduardo Ribeiro', '00000000048', 'usuario48@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gerente de Operações', 'gestor', 48);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (49, 'usuario49', 45, 'Camila Almeida', '00000000049', 'usuario49@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Gestor de Qualidade', 'gestor', 49);
INSERT INTO Usuario (id_usuario, username, cod_gestor, nome, cpf, email, senha, cargo, nivel_acesso, id_cd) VALUES (50, 'usuario50', NULL, 'Lucas Nunes', '00000000050', 'usuario50@logfresh.com', '$2b$10$KIXq3nPZ0fQe7uYwR1sT8eJ4vXhLmN2oPa6bCdE9fGhIjKlMnOpQr', 'Administrador de Sistema', 'admin', 50);

-- FRIGORIFICO

INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (1, 'Freezer Industrial 1', 'Setor A - Corredor 1', 1);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (2, 'Freezer Industrial 2', 'Setor B - Corredor 2', 2);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (3, 'Câmara Fria - Carnes 3', 'Setor C - Corredor 3', 3);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (4, 'Câmara Fria - Aves 4', 'Setor D - Corredor 4', 4);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (5, 'Freezer Industrial 5', 'Setor A - Corredor 5', 5);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (6, 'Câmara Fria - Carnes 6', 'Setor B - Corredor 6', 6);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (7, 'Freezer Industrial 7', 'Setor C - Corredor 1', 7);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (8, 'Freezer Industrial 8', 'Setor D - Corredor 2', 8);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (9, 'Câmara Fria - Aves 9', 'Setor A - Corredor 3', 9);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (10, 'Câmara Fria - Carnes 10', 'Setor B - Corredor 4', 10);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (11, 'Freezer Industrial 11', 'Setor C - Corredor 5', 11);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (12, 'Freezer Industrial 12', 'Setor D - Corredor 6', 12);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (13, 'Câmara Fria - Carnes 13', 'Setor A - Corredor 1', 13);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (14, 'Câmara Fria - Aves 14', 'Setor B - Corredor 2', 14);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (15, 'Freezer Industrial 15', 'Setor C - Corredor 3', 15);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (16, 'Câmara Fria - Carnes 16', 'Setor D - Corredor 4', 16);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (17, 'Freezer Industrial 17', 'Setor A - Corredor 5', 17);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (18, 'Freezer Industrial 18', 'Setor B - Corredor 6', 18);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (19, 'Câmara Fria - Aves 19', 'Setor C - Corredor 1', 19);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (20, 'Câmara Fria - Carnes 20', 'Setor D - Corredor 2', 20);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (21, 'Freezer Industrial 21', 'Setor A - Corredor 3', 21);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (22, 'Freezer Industrial 22', 'Setor B - Corredor 4', 22);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (23, 'Câmara Fria - Carnes 23', 'Setor C - Corredor 5', 23);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (24, 'Câmara Fria - Aves 24', 'Setor D - Corredor 6', 24);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (25, 'Freezer Industrial 25', 'Setor A - Corredor 1', 25);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (26, 'Câmara Fria - Carnes 26', 'Setor B - Corredor 2', 26);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (27, 'Câmara Fria - Aves 27', 'Setor C - Corredor 3', 27);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (28, 'Freezer Industrial 28', 'Setor D - Corredor 4', 28);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (29, 'Freezer Industrial 29', 'Setor A - Corredor 5', 29);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (30, 'Câmara Fria - Carnes 30', 'Setor B - Corredor 6', 30);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (31, 'Freezer Industrial 31', 'Setor C - Corredor 1', 31);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (32, 'Câmara Fria - Aves 32', 'Setor D - Corredor 2', 32);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (33, 'Câmara Fria - Carnes 33', 'Setor A - Corredor 3', 33);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (34, 'Freezer Industrial 34', 'Setor B - Corredor 4', 34);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (35, 'Freezer Industrial 35', 'Setor C - Corredor 5', 35);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (36, 'Câmara Fria - Carnes 36', 'Setor D - Corredor 6', 36);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (37, 'Câmara Fria - Aves 37', 'Setor A - Corredor 1', 37);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (38, 'Freezer Industrial 38', 'Setor B - Corredor 2', 38);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (39, 'Freezer Industrial 39', 'Setor C - Corredor 3', 39);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (40, 'Câmara Fria - Carnes 40', 'Setor D - Corredor 4', 40);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (41, 'Freezer Industrial 41', 'Setor A - Corredor 5', 41);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (42, 'Câmara Fria - Aves 42', 'Setor B - Corredor 6', 42);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (43, 'Câmara Fria - Carnes 43', 'Setor C - Corredor 1', 43);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (44, 'Freezer Industrial 44', 'Setor D - Corredor 2', 44);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (45, 'Freezer Industrial 45', 'Setor A - Corredor 3', 45);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (46, 'Câmara Fria - Carnes 46', 'Setor B - Corredor 4', 46);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (47, 'Câmara Fria - Aves 47', 'Setor C - Corredor 5', 47);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (48, 'Freezer Industrial 48', 'Setor D - Corredor 6', 48);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (49, 'Freezer Industrial 49', 'Setor A - Corredor 1', 49);
INSERT INTO Frigorifico (id_frigorifico, nome, localizacao, id_cd) VALUES (50, 'Câmara Fria - Carnes 50', 'Setor B - Corredor 2', 50);

-- TERMOMETRO

INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (1, 'Sensor DHT-2200', 'ativo', 1);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (2, 'Sensor TempLog X3', 'ativo', 2);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (3, 'Sensor TermoSense Pro', 'ativo', 3);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (4, 'Sensor IoT-Cold', 'ativo', 4);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (5, 'Sensor ThermoGuard', 'manutencao', 5);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (6, 'Sensor DHT-2200', 'ativo', 6);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (7, 'Sensor TempLog X3', 'ativo', 7);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (8, 'Sensor TermoSense Pro', 'ativo', 8);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (9, 'Sensor IoT-Cold', 'ativo', 9);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (10, 'Sensor ThermoGuard', 'inativo', 10);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (11, 'Sensor DHT-2200', 'ativo', 11);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (12, 'Sensor TempLog X3', 'ativo', 12);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (13, 'Sensor TermoSense Pro', 'ativo', 13);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (14, 'Sensor IoT-Cold', 'ativo', 14);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (15, 'Sensor ThermoGuard', 'manutencao', 15);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (16, 'Sensor DHT-2200', 'ativo', 16);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (17, 'Sensor TempLog X3', 'ativo', 17);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (18, 'Sensor TermoSense Pro', 'ativo', 18);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (19, 'Sensor IoT-Cold', 'ativo', 19);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (20, 'Sensor ThermoGuard', 'inativo', 20);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (21, 'Sensor DHT-2200', 'ativo', 21);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (22, 'Sensor TempLog X3', 'ativo', 22);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (23, 'Sensor TermoSense Pro', 'ativo', 23);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (24, 'Sensor IoT-Cold', 'ativo', 24);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (25, 'Sensor ThermoGuard', 'manutencao', 25);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (26, 'Sensor DHT-2200', 'ativo', 26);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (27, 'Sensor TempLog X3', 'ativo', 27);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (28, 'Sensor TermoSense Pro', 'ativo', 28);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (29, 'Sensor IoT-Cold', 'ativo', 29);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (30, 'Sensor ThermoGuard', 'inativo', 30);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (31, 'Sensor DHT-2200', 'ativo', 31);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (32, 'Sensor TempLog X3', 'ativo', 32);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (33, 'Sensor TermoSense Pro', 'ativo', 33);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (34, 'Sensor IoT-Cold', 'ativo', 34);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (35, 'Sensor ThermoGuard', 'manutencao', 35);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (36, 'Sensor DHT-2200', 'ativo', 36);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (37, 'Sensor TempLog X3', 'ativo', 37);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (38, 'Sensor TermoSense Pro', 'ativo', 38);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (39, 'Sensor IoT-Cold', 'ativo', 39);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (40, 'Sensor ThermoGuard', 'inativo', 40);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (41, 'Sensor DHT-2200', 'ativo', 41);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (42, 'Sensor TempLog X3', 'ativo', 42);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (43, 'Sensor TermoSense Pro', 'ativo', 43);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (44, 'Sensor IoT-Cold', 'ativo', 44);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (45, 'Sensor ThermoGuard', 'manutencao', 45);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (46, 'Sensor DHT-2200', 'ativo', 46);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (47, 'Sensor TempLog X3', 'ativo', 47);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (48, 'Sensor TermoSense Pro', 'ativo', 48);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (49, 'Sensor IoT-Cold', 'ativo', 49);
INSERT INTO Termometro (id_termometro, modelo, status, id_frigorifico) VALUES (50, 'Sensor ThermoGuard', 'inativo', 50);

-- CATEGORIA

INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (1, 'Picanha Bovina Friboi Congelada', 3.20, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (2, 'Peito de Frango Seara Congelado', 2.25, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (3, 'Alcatra Bovina Friboi Resfriada', 0.92, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (4, 'Coxa e Sobrecoxa de Frango Seara Resfriadas', 0.56, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (5, 'Contra Filé Bovino Friboi Congelado', 3.30, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (6, 'Filé Mignon Bovino Friboi Resfriado', 0.96, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (7, 'Filé de Frango Seara Congelado', 2.31, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (8, 'Fraldinha Bovina Friboi Congelada', 3.40, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (9, 'Asa de Frango Seara Resfriada', 0.58, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (10, 'Maminha Bovina Friboi Resfriada', 1.00, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (11, 'Patinho Bovino Friboi Congelado', 3.50, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (12, 'Frango Inteiro Seara Congelado', 2.37, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (13, 'Coxão Mole Bovino Friboi Resfriado', 1.04, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (14, 'Coxinha da Asa de Frango Seara Resfriada', 0.60, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (15, 'Coxão Duro Bovino Friboi Congelado', 3.60, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (16, 'Acém Bovino Friboi Resfriado', 1.08, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (17, 'Sobrecoxa de Frango Seara Congelada', 2.43, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (18, 'Cupim Bovino Friboi Congelado', 3.70, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (19, 'Tulipa de Frango Seara Resfriada', 0.62, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (20, 'Costela Bovina Friboi Resfriada', 1.12, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (21, 'Paleta Bovina Friboi Congelada', 3.80, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (22, 'Frango a Passarinho Seara Congelado', 2.49, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (23, 'Músculo Bovino Friboi Resfriado', 1.16, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (24, 'Frango Desossado Seara Resfriado', 0.64, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (25, 'Lagarto Bovino Friboi Congelado', 3.90, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (26, 'Picanha Bovina Swift Resfriada', 0.90, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (27, 'Peito de Frango Seara Resfriado', 0.55, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (28, 'Alcatra Bovina Swift Congelada', 3.25, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (29, 'Coxa e Sobrecoxa de Frango Seara Congeladas', 2.28, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (30, 'Contra Filé Bovino Swift Resfriado', 0.94, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (31, 'Filé Mignon Bovino Swift Congelado', 3.35, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (32, 'Filé de Frango Seara Resfriado', 0.57, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (33, 'Fraldinha Bovina Swift Resfriada', 0.98, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (34, 'Asa de Frango Seara Congelada', 2.34, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (35, 'Maminha Bovina Swift Congelada', 3.45, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (36, 'Patinho Bovino Swift Resfriado', 1.02, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (37, 'Frango Inteiro Seara Resfriado', 0.59, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (38, 'Coxão Mole Bovino Swift Congelado', 3.55, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (39, 'Coxinha da Asa de Frango Seara Congelada', 2.40, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (40, 'Coxão Duro Bovino Swift Resfriado', 1.06, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (41, 'Acém Bovino Swift Congelado', 3.65, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (42, 'Sobrecoxa de Frango Seara Resfriada', 0.61, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (43, 'Cupim Bovino Swift Resfriado', 1.10, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (44, 'Tulipa de Frango Seara Congelada', 2.46, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (45, 'Costela Bovina Swift Congelada', 3.75, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (46, 'Paleta Bovina Swift Resfriada', 1.14, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (47, 'Frango a Passarinho Seara Resfriado', 0.63, 4.00, 0.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (48, 'Músculo Bovino Swift Congelado', 3.85, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (49, 'Frango Desossado Seara Congelado', 2.52, -18.00, -25.00);
INSERT INTO Categoria (id_categoria, nome, vida_util_horas, temperatura_max, temperatura_min) VALUES (50, 'Lagarto Bovino Swift Resfriado', 1.18, 4.00, 0.00);

-- LOTE

INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (1, 'LT-FRB-2026-0001', 1, CURRENT_DATE - 23, CURRENT_DATE + 157, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (2, 'LT-SEA-2026-0002', 2, CURRENT_DATE - 26, CURRENT_DATE + 154, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (3, 'LT-FRB-2026-0003', 3, CURRENT_DATE - 6, CURRENT_DATE + 4, 'bloqueado');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (4, 'LT-SEA-2026-0004', 4, CURRENT_DATE - 7, CURRENT_DATE + 3, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (5, 'LT-FRB-2026-0005', 5, CURRENT_DATE - 35, CURRENT_DATE + 145, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (6, 'LT-FRB-2026-0006', 6, CURRENT_DATE - 6, CURRENT_DATE + 4, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (7, 'LT-SEA-2026-0007', 7, CURRENT_DATE - 207, CURRENT_DATE - 27, 'vencido');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (8, 'LT-FRB-2026-0008', 8, CURRENT_DATE - 44, CURRENT_DATE + 136, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (9, 'LT-SEA-2026-0009', 9, CURRENT_DATE - 6, CURRENT_DATE + 4, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (10, 'LT-FRB-2026-0010', 10, CURRENT_DATE - 7, CURRENT_DATE + 3, 'expedido');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (11, 'LT-FRB-2026-0011', 11, CURRENT_DATE - 53, CURRENT_DATE + 127, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (12, 'LT-SEA-2026-0012', 12, CURRENT_DATE - 56, CURRENT_DATE + 124, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (13, 'LT-FRB-2026-0013', 13, CURRENT_DATE - 7, CURRENT_DATE + 3, 'bloqueado');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (14, 'LT-SEA-2026-0014', 14, CURRENT_DATE - 8, CURRENT_DATE + 2, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (15, 'LT-FRB-2026-0015', 15, CURRENT_DATE - 25, CURRENT_DATE + 155, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (16, 'LT-FRB-2026-0016', 16, CURRENT_DATE - 7, CURRENT_DATE + 3, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (17, 'LT-SEA-2026-0017', 17, CURRENT_DATE - 207, CURRENT_DATE - 27, 'vencido');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (18, 'LT-FRB-2026-0018', 18, CURRENT_DATE - 34, CURRENT_DATE + 146, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (19, 'LT-SEA-2026-0019', 19, CURRENT_DATE - 7, CURRENT_DATE + 3, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (20, 'LT-FRB-2026-0020', 20, CURRENT_DATE - 8, CURRENT_DATE + 2, 'expedido');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (21, 'LT-FRB-2026-0021', 21, CURRENT_DATE - 43, CURRENT_DATE + 137, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (22, 'LT-SEA-2026-0022', 22, CURRENT_DATE - 46, CURRENT_DATE + 134, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (23, 'LT-FRB-2026-0023', 23, CURRENT_DATE - 8, CURRENT_DATE + 2, 'bloqueado');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (24, 'LT-SEA-2026-0024', 24, CURRENT_DATE - 6, CURRENT_DATE + 4, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (25, 'LT-FRB-2026-0025', 25, CURRENT_DATE - 55, CURRENT_DATE + 125, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (26, 'LT-SWF-2026-0026', 26, CURRENT_DATE - 8, CURRENT_DATE + 2, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (27, 'LT-SEA-2026-0027', 27, CURRENT_DATE - 207, CURRENT_DATE - 197, 'vencido');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (28, 'LT-SWF-2026-0028', 28, CURRENT_DATE - 24, CURRENT_DATE + 156, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (29, 'LT-SEA-2026-0029', 29, CURRENT_DATE - 27, CURRENT_DATE + 153, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (30, 'LT-SWF-2026-0030', 30, CURRENT_DATE - 6, CURRENT_DATE + 4, 'expedido');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (31, 'LT-SWF-2026-0031', 31, CURRENT_DATE - 33, CURRENT_DATE + 147, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (32, 'LT-SEA-2026-0032', 32, CURRENT_DATE - 8, CURRENT_DATE + 2, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (33, 'LT-SWF-2026-0033', 33, CURRENT_DATE - 6, CURRENT_DATE + 4, 'bloqueado');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (34, 'LT-SEA-2026-0034', 34, CURRENT_DATE - 42, CURRENT_DATE + 138, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (35, 'LT-SWF-2026-0035', 35, CURRENT_DATE - 45, CURRENT_DATE + 135, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (36, 'LT-SWF-2026-0036', 36, CURRENT_DATE - 6, CURRENT_DATE + 4, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (37, 'LT-SEA-2026-0037', 37, CURRENT_DATE - 207, CURRENT_DATE - 197, 'vencido');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (38, 'LT-SWF-2026-0038', 38, CURRENT_DATE - 54, CURRENT_DATE + 126, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (39, 'LT-SEA-2026-0039', 39, CURRENT_DATE - 57, CURRENT_DATE + 123, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (40, 'LT-SWF-2026-0040', 40, CURRENT_DATE - 7, CURRENT_DATE + 3, 'expedido');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (41, 'LT-SWF-2026-0041', 41, CURRENT_DATE - 23, CURRENT_DATE + 157, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (42, 'LT-SEA-2026-0042', 42, CURRENT_DATE - 6, CURRENT_DATE + 4, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (43, 'LT-SWF-2026-0043', 43, CURRENT_DATE - 7, CURRENT_DATE + 3, 'bloqueado');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (44, 'LT-SEA-2026-0044', 44, CURRENT_DATE - 32, CURRENT_DATE + 148, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (45, 'LT-SWF-2026-0045', 45, CURRENT_DATE - 35, CURRENT_DATE + 145, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (46, 'LT-SWF-2026-0046', 46, CURRENT_DATE - 7, CURRENT_DATE + 3, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (47, 'LT-SEA-2026-0047', 47, CURRENT_DATE - 207, CURRENT_DATE - 197, 'vencido');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (48, 'LT-SWF-2026-0048', 48, CURRENT_DATE - 44, CURRENT_DATE + 136, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (49, 'LT-SEA-2026-0049', 49, CURRENT_DATE - 47, CURRENT_DATE + 133, 'ativo');
INSERT INTO Lote (id_lote, codigo_lote, id_categoria, data_fabricacao, data_validade, status) VALUES (50, 'LT-SWF-2026-0050', 50, CURRENT_DATE - 8, CURRENT_DATE + 2, 'expedido');

-- LOTE_FRIGORIFICO

INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (1, 1, 1, CURRENT_TIMESTAMP - INTERVAL '22 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (2, 2, 2, CURRENT_TIMESTAMP - INTERVAL '25 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (3, 3, 3, CURRENT_TIMESTAMP - INTERVAL '5 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (4, 4, 4, CURRENT_TIMESTAMP - INTERVAL '6 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (5, 5, 5, CURRENT_TIMESTAMP - INTERVAL '34 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (6, 6, 6, CURRENT_TIMESTAMP - INTERVAL '5 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (7, 7, 7, CURRENT_TIMESTAMP - INTERVAL '206 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (8, 8, 8, CURRENT_TIMESTAMP - INTERVAL '43 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (9, 9, 9, CURRENT_TIMESTAMP - INTERVAL '5 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (10, 10, 10, CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '4 days');
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (11, 11, 11, CURRENT_TIMESTAMP - INTERVAL '52 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (12, 12, 12, CURRENT_TIMESTAMP - INTERVAL '55 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (13, 13, 13, CURRENT_TIMESTAMP - INTERVAL '6 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (14, 14, 14, CURRENT_TIMESTAMP - INTERVAL '7 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (15, 15, 15, CURRENT_TIMESTAMP - INTERVAL '24 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (16, 16, 16, CURRENT_TIMESTAMP - INTERVAL '6 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (17, 17, 17, CURRENT_TIMESTAMP - INTERVAL '206 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (18, 18, 18, CURRENT_TIMESTAMP - INTERVAL '33 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (19, 19, 19, CURRENT_TIMESTAMP - INTERVAL '6 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (20, 20, 20, CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP - INTERVAL '4 days');
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (21, 21, 21, CURRENT_TIMESTAMP - INTERVAL '42 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (22, 22, 22, CURRENT_TIMESTAMP - INTERVAL '45 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (23, 23, 23, CURRENT_TIMESTAMP - INTERVAL '7 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (24, 24, 24, CURRENT_TIMESTAMP - INTERVAL '5 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (25, 25, 25, CURRENT_TIMESTAMP - INTERVAL '54 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (26, 26, 26, CURRENT_TIMESTAMP - INTERVAL '7 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (27, 27, 27, CURRENT_TIMESTAMP - INTERVAL '206 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (28, 28, 28, CURRENT_TIMESTAMP - INTERVAL '23 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (29, 29, 29, CURRENT_TIMESTAMP - INTERVAL '26 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (30, 30, 30, CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '4 days');
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (31, 31, 31, CURRENT_TIMESTAMP - INTERVAL '32 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (32, 32, 32, CURRENT_TIMESTAMP - INTERVAL '7 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (33, 33, 33, CURRENT_TIMESTAMP - INTERVAL '5 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (34, 34, 34, CURRENT_TIMESTAMP - INTERVAL '41 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (35, 35, 35, CURRENT_TIMESTAMP - INTERVAL '44 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (36, 36, 36, CURRENT_TIMESTAMP - INTERVAL '5 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (37, 37, 37, CURRENT_TIMESTAMP - INTERVAL '206 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (38, 38, 38, CURRENT_TIMESTAMP - INTERVAL '53 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (39, 39, 39, CURRENT_TIMESTAMP - INTERVAL '56 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (40, 40, 40, CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '4 days');
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (41, 41, 41, CURRENT_TIMESTAMP - INTERVAL '22 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (42, 42, 42, CURRENT_TIMESTAMP - INTERVAL '5 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (43, 43, 43, CURRENT_TIMESTAMP - INTERVAL '6 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (44, 44, 44, CURRENT_TIMESTAMP - INTERVAL '31 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (45, 45, 45, CURRENT_TIMESTAMP - INTERVAL '34 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (46, 46, 46, CURRENT_TIMESTAMP - INTERVAL '6 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (47, 47, 47, CURRENT_TIMESTAMP - INTERVAL '206 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (48, 48, 48, CURRENT_TIMESTAMP - INTERVAL '43 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (49, 49, 49, CURRENT_TIMESTAMP - INTERVAL '46 days', NULL);
INSERT INTO lote_frigorifico (id_lote_frigorifico, id_lote, id_frigorifico, data_entrada, data_saida) VALUES (50, 50, 50, CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP - INTERVAL '4 days');

-- LEITURATEMPERATURA

INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (1, -16.30, CURRENT_TIMESTAMP - INTERVAL '277 minutes', 1);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (2, -15.60, CURRENT_TIMESTAMP - INTERVAL '374 minutes', 2);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (3, 6.60, CURRENT_TIMESTAMP - INTERVAL '471 minutes', 3);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (4, -3.80, CURRENT_TIMESTAMP - INTERVAL '568 minutes', 4);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (5, -21.30, CURRENT_TIMESTAMP - INTERVAL '665 minutes', 5);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (6, -5.20, CURRENT_TIMESTAMP - INTERVAL '762 minutes', 6);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (7, -16.60, CURRENT_TIMESTAMP - INTERVAL '859 minutes', 7);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (8, -17.20, CURRENT_TIMESTAMP - INTERVAL '956 minutes', 8);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (9, 6.80, CURRENT_TIMESTAMP - INTERVAL '1053 minutes', 9);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (10, 2.40, CURRENT_TIMESTAMP - INTERVAL '1150 minutes', 10);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (11, -13.80, CURRENT_TIMESTAMP - INTERVAL '1247 minutes', 11);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (12, -13.10, CURRENT_TIMESTAMP - INTERVAL '1344 minutes', 12);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (13, 5.40, CURRENT_TIMESTAMP - INTERVAL '1441 minutes', 13);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (14, -1.80, CURRENT_TIMESTAMP - INTERVAL '1538 minutes', 14);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (15, -21.50, CURRENT_TIMESTAMP - INTERVAL '1635 minutes', 15);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (16, -3.20, CURRENT_TIMESTAMP - INTERVAL '1732 minutes', 16);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (17, -14.10, CURRENT_TIMESTAMP - INTERVAL '1829 minutes', 17);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (18, -16.00, CURRENT_TIMESTAMP - INTERVAL '1926 minutes', 18);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (19, 9.30, CURRENT_TIMESTAMP - INTERVAL '2023 minutes', 19);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (20, 2.00, CURRENT_TIMESTAMP - INTERVAL '2120 minutes', 20);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (21, -15.80, CURRENT_TIMESTAMP - INTERVAL '2217 minutes', 21);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (22, -15.10, CURRENT_TIMESTAMP - INTERVAL '2314 minutes', 22);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (23, 6.60, CURRENT_TIMESTAMP - INTERVAL '2411 minutes', 23);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (24, -4.30, CURRENT_TIMESTAMP - INTERVAL '2508 minutes', 24);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (25, -21.40, CURRENT_TIMESTAMP - INTERVAL '2605 minutes', 25);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (26, -1.20, CURRENT_TIMESTAMP - INTERVAL '2702 minutes', 26);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (27, 5.90, CURRENT_TIMESTAMP - INTERVAL '2799 minutes', 27);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (28, -17.20, CURRENT_TIMESTAMP - INTERVAL '2896 minutes', 28);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (29, -14.70, CURRENT_TIMESTAMP - INTERVAL '2993 minutes', 29);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (30, 2.40, CURRENT_TIMESTAMP - INTERVAL '3090 minutes', 30);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (31, -13.30, CURRENT_TIMESTAMP - INTERVAL '3187 minutes', 31);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (32, -5.40, CURRENT_TIMESTAMP - INTERVAL '3284 minutes', 32);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (33, 5.40, CURRENT_TIMESTAMP - INTERVAL '3381 minutes', 33);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (34, -15.70, CURRENT_TIMESTAMP - INTERVAL '3478 minutes', 34);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (35, -21.30, CURRENT_TIMESTAMP - INTERVAL '3575 minutes', 35);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (36, -3.70, CURRENT_TIMESTAMP - INTERVAL '3672 minutes', 36);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (37, 8.40, CURRENT_TIMESTAMP - INTERVAL '3769 minutes', 37);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (38, -16.00, CURRENT_TIMESTAMP - INTERVAL '3866 minutes', 38);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (39, -16.70, CURRENT_TIMESTAMP - INTERVAL '3963 minutes', 39);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (40, 2.00, CURRENT_TIMESTAMP - INTERVAL '4060 minutes', 40);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (41, -15.30, CURRENT_TIMESTAMP - INTERVAL '4157 minutes', 41);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (42, -3.40, CURRENT_TIMESTAMP - INTERVAL '4254 minutes', 42);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (43, 6.60, CURRENT_TIMESTAMP - INTERVAL '4351 minutes', 43);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (44, -13.20, CURRENT_TIMESTAMP - INTERVAL '4448 minutes', 44);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (45, -21.50, CURRENT_TIMESTAMP - INTERVAL '4545 minutes', 45);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (46, -1.70, CURRENT_TIMESTAMP - INTERVAL '4642 minutes', 46);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (47, 6.40, CURRENT_TIMESTAMP - INTERVAL '4739 minutes', 47);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (48, -17.20, CURRENT_TIMESTAMP - INTERVAL '4836 minutes', 48);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (49, -14.20, CURRENT_TIMESTAMP - INTERVAL '4933 minutes', 49);
INSERT INTO LeituraTemperatura (id_leitura, temperatura, data_hora, id_termometro) VALUES (50, 2.40, CURRENT_TIMESTAMP - INTERVAL '5030 minutes', 50);

-- ALERTA

INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (1, 'temperatura_fora_padrao', 'medio', 'pendente', 134, CURRENT_TIMESTAMP - INTERVAL '275 minutes', NULL, 1, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (2, 'temperatura_fora_padrao', 'medio', 'em_andamento', 94, CURRENT_TIMESTAMP - INTERVAL '372 minutes', NULL, 2, 2);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (3, 'porta_aberta', 'medio', 'resolvido', 39, CURRENT_TIMESTAMP - INTERVAL '469 minutes', CURRENT_TIMESTAMP - INTERVAL '405 minutes', 3, 3);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (4, 'temperatura_fora_padrao', 'alto', 'ignorado', 17, CURRENT_TIMESTAMP - INTERVAL '566 minutes', CURRENT_TIMESTAMP - INTERVAL '489 minutes', 4, 4);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (5, 'termometro_offline', 'medio', 'pendente', NULL, CURRENT_TIMESTAMP - INTERVAL '663 minutes', NULL, 5, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (6, 'temperatura_fora_padrao', 'critico', 'em_andamento', 17, CURRENT_TIMESTAMP - INTERVAL '760 minutes', NULL, 6, 6);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (7, 'temperatura_fora_padrao', 'baixo', 'resolvido', 125, CURRENT_TIMESTAMP - INTERVAL '857 minutes', CURRENT_TIMESTAMP - INTERVAL '832 minutes', 7, 7);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (8, 'porta_aberta', 'baixo', 'ignorado', 184, CURRENT_TIMESTAMP - INTERVAL '954 minutes', CURRENT_TIMESTAMP - INTERVAL '916 minutes', 8, 8);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (9, 'temperatura_fora_padrao', 'medio', 'pendente', 24, CURRENT_TIMESTAMP - INTERVAL '1051 minutes', NULL, 9, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (10, 'termometro_offline', 'alto', 'em_andamento', NULL, CURRENT_TIMESTAMP - INTERVAL '1148 minutes', NULL, 10, 10);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (11, 'temperatura_fora_padrao', 'alto', 'resolvido', 105, CURRENT_TIMESTAMP - INTERVAL '1245 minutes', CURRENT_TIMESTAMP - INTERVAL '1168 minutes', 11, 11);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (12, 'temperatura_fora_padrao', 'critico', 'ignorado', 43, CURRENT_TIMESTAMP - INTERVAL '1342 minutes', CURRENT_TIMESTAMP - INTERVAL '1252 minutes', 12, 12);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (13, 'porta_aberta', 'baixo', 'pendente', 56, CURRENT_TIMESTAMP - INTERVAL '1439 minutes', NULL, 13, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (14, 'temperatura_fora_padrao', 'medio', 'em_andamento', 25, CURRENT_TIMESTAMP - INTERVAL '1536 minutes', NULL, 14, 14);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (15, 'termometro_offline', 'medio', 'resolvido', NULL, CURRENT_TIMESTAMP - INTERVAL '1633 minutes', CURRENT_TIMESTAMP - INTERVAL '1595 minutes', 15, 15);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (16, 'temperatura_fora_padrao', 'alto', 'ignorado', 32, CURRENT_TIMESTAMP - INTERVAL '1730 minutes', CURRENT_TIMESTAMP - INTERVAL '1679 minutes', 16, 16);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (17, 'temperatura_fora_padrao', 'alto', 'pendente', 73, CURRENT_TIMESTAMP - INTERVAL '1827 minutes', NULL, 17, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (18, 'porta_aberta', 'medio', 'em_andamento', 155, CURRENT_TIMESTAMP - INTERVAL '1924 minutes', NULL, 18, 18);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (19, 'temperatura_fora_padrao', 'critico', 'resolvido', 11, CURRENT_TIMESTAMP - INTERVAL '2021 minutes', CURRENT_TIMESTAMP - INTERVAL '1931 minutes', 19, 19);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (20, 'termometro_offline', 'alto', 'ignorado', NULL, CURRENT_TIMESTAMP - INTERVAL '2118 minutes', CURRENT_TIMESTAMP - INTERVAL '2015 minutes', 20, 20);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (21, 'temperatura_fora_padrao', 'medio', 'pendente', 160, CURRENT_TIMESTAMP - INTERVAL '2215 minutes', NULL, 21, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (22, 'temperatura_fora_padrao', 'medio', 'em_andamento', 105, CURRENT_TIMESTAMP - INTERVAL '2312 minutes', NULL, 22, 22);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (23, 'porta_aberta', 'medio', 'resolvido', 49, CURRENT_TIMESTAMP - INTERVAL '2409 minutes', CURRENT_TIMESTAMP - INTERVAL '2358 minutes', 23, 23);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (24, 'temperatura_fora_padrao', 'alto', 'ignorado', 19, CURRENT_TIMESTAMP - INTERVAL '2506 minutes', CURRENT_TIMESTAMP - INTERVAL '2442 minutes', 24, 24);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (25, 'termometro_offline', 'medio', 'pendente', NULL, CURRENT_TIMESTAMP - INTERVAL '2603 minutes', NULL, 25, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (26, 'temperatura_fora_padrao', 'baixo', 'em_andamento', 49, CURRENT_TIMESTAMP - INTERVAL '2700 minutes', NULL, 26, 26);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (27, 'temperatura_fora_padrao', 'medio', 'resolvido', 23, CURRENT_TIMESTAMP - INTERVAL '2797 minutes', CURRENT_TIMESTAMP - INTERVAL '2694 minutes', 27, 27);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (28, 'porta_aberta', 'baixo', 'ignorado', 176, CURRENT_TIMESTAMP - INTERVAL '2894 minutes', CURRENT_TIMESTAMP - INTERVAL '2869 minutes', 28, 28);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (29, 'temperatura_fora_padrao', 'alto', 'pendente', 68, CURRENT_TIMESTAMP - INTERVAL '2991 minutes', NULL, 29, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (30, 'termometro_offline', 'alto', 'em_andamento', NULL, CURRENT_TIMESTAMP - INTERVAL '3088 minutes', NULL, 30, 30);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (31, 'temperatura_fora_padrao', 'critico', 'resolvido', 60, CURRENT_TIMESTAMP - INTERVAL '3185 minutes', CURRENT_TIMESTAMP - INTERVAL '3121 minutes', 31, 31);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (32, 'temperatura_fora_padrao', 'critico', 'ignorado', 10, CURRENT_TIMESTAMP - INTERVAL '3282 minutes', CURRENT_TIMESTAMP - INTERVAL '3205 minutes', 32, 32);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (33, 'porta_aberta', 'baixo', 'pendente', 53, CURRENT_TIMESTAMP - INTERVAL '3379 minutes', NULL, 33, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (34, 'temperatura_fora_padrao', 'medio', 'em_andamento', 98, CURRENT_TIMESTAMP - INTERVAL '3476 minutes', NULL, 34, 34);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (35, 'termometro_offline', 'medio', 'resolvido', NULL, CURRENT_TIMESTAMP - INTERVAL '3573 minutes', CURRENT_TIMESTAMP - INTERVAL '3548 minutes', 35, 35);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (36, 'temperatura_fora_padrao', 'alto', 'ignorado', 31, CURRENT_TIMESTAMP - INTERVAL '3670 minutes', CURRENT_TIMESTAMP - INTERVAL '3632 minutes', 36, 36);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (37, 'temperatura_fora_padrao', 'alto', 'pendente', 18, CURRENT_TIMESTAMP - INTERVAL '3767 minutes', NULL, 37, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (38, 'porta_aberta', 'medio', 'em_andamento', 149, CURRENT_TIMESTAMP - INTERVAL '3864 minutes', NULL, 38, 38);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (39, 'temperatura_fora_padrao', 'baixo', 'resolvido', 130, CURRENT_TIMESTAMP - INTERVAL '3961 minutes', CURRENT_TIMESTAMP - INTERVAL '3884 minutes', 39, 39);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (40, 'termometro_offline', 'alto', 'ignorado', NULL, CURRENT_TIMESTAMP - INTERVAL '4058 minutes', CURRENT_TIMESTAMP - INTERVAL '3968 minutes', 40, 40);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (41, 'temperatura_fora_padrao', 'medio', 'pendente', 153, CURRENT_TIMESTAMP - INTERVAL '4155 minutes', NULL, 41, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (42, 'temperatura_fora_padrao', 'alto', 'em_andamento', 18, CURRENT_TIMESTAMP - INTERVAL '4252 minutes', NULL, 42, 42);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (43, 'porta_aberta', 'medio', 'resolvido', 46, CURRENT_TIMESTAMP - INTERVAL '4349 minutes', CURRENT_TIMESTAMP - INTERVAL '4311 minutes', 43, 43);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (44, 'temperatura_fora_padrao', 'critico', 'ignorado', 44, CURRENT_TIMESTAMP - INTERVAL '4446 minutes', CURRENT_TIMESTAMP - INTERVAL '4395 minutes', 44, 44);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (45, 'termometro_offline', 'medio', 'pendente', NULL, CURRENT_TIMESTAMP - INTERVAL '4543 minutes', NULL, 45, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (46, 'temperatura_fora_padrao', 'medio', 'em_andamento', 48, CURRENT_TIMESTAMP - INTERVAL '4640 minutes', NULL, 46, 46);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (47, 'temperatura_fora_padrao', 'medio', 'resolvido', 26, CURRENT_TIMESTAMP - INTERVAL '4737 minutes', CURRENT_TIMESTAMP - INTERVAL '4647 minutes', 47, 47);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (48, 'porta_aberta', 'baixo', 'ignorado', 208, CURRENT_TIMESTAMP - INTERVAL '4834 minutes', CURRENT_TIMESTAMP - INTERVAL '4731 minutes', 48, 48);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (49, 'temperatura_fora_padrao', 'alto', 'pendente', 76, CURRENT_TIMESTAMP - INTERVAL '4931 minutes', NULL, 49, NULL);
INSERT INTO Alerta (id_alerta, tipo, nivel_gravidade, status, vida_util, data_hora, data_hora_resolucao, id_leitura, id_usuario) VALUES (50, 'termometro_offline', 'alto', 'em_andamento', NULL, CURRENT_TIMESTAMP - INTERVAL '5028 minutes', NULL, 50, 50);

-- NOTIFICACAOALERTA 

INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (1, 1, 1, CURRENT_TIMESTAMP - INTERVAL '274 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (2, 2, 2, CURRENT_TIMESTAMP - INTERVAL '371 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (3, 3, 3, CURRENT_TIMESTAMP - INTERVAL '468 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (4, 4, 4, CURRENT_TIMESTAMP - INTERVAL '565 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (5, 5, 5, CURRENT_TIMESTAMP - INTERVAL '662 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (6, 6, 6, CURRENT_TIMESTAMP - INTERVAL '759 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (7, 7, 7, CURRENT_TIMESTAMP - INTERVAL '856 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (8, 8, 8, CURRENT_TIMESTAMP - INTERVAL '953 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (9, 9, 9, CURRENT_TIMESTAMP - INTERVAL '1050 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (10, 10, 10, CURRENT_TIMESTAMP - INTERVAL '1147 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (11, 11, 11, CURRENT_TIMESTAMP - INTERVAL '1244 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (12, 12, 12, CURRENT_TIMESTAMP - INTERVAL '1341 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (13, 13, 13, CURRENT_TIMESTAMP - INTERVAL '1438 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (14, 14, 14, CURRENT_TIMESTAMP - INTERVAL '1535 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (15, 15, 15, CURRENT_TIMESTAMP - INTERVAL '1632 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (16, 16, 16, CURRENT_TIMESTAMP - INTERVAL '1729 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (17, 17, 17, CURRENT_TIMESTAMP - INTERVAL '1826 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (18, 18, 18, CURRENT_TIMESTAMP - INTERVAL '1923 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (19, 19, 19, CURRENT_TIMESTAMP - INTERVAL '2020 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (20, 20, 20, CURRENT_TIMESTAMP - INTERVAL '2117 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (21, 21, 21, CURRENT_TIMESTAMP - INTERVAL '2214 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (22, 22, 22, CURRENT_TIMESTAMP - INTERVAL '2311 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (23, 23, 23, CURRENT_TIMESTAMP - INTERVAL '2408 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (24, 24, 24, CURRENT_TIMESTAMP - INTERVAL '2505 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (25, 25, 25, CURRENT_TIMESTAMP - INTERVAL '2602 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (26, 26, 26, CURRENT_TIMESTAMP - INTERVAL '2699 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (27, 27, 27, CURRENT_TIMESTAMP - INTERVAL '2796 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (28, 28, 28, CURRENT_TIMESTAMP - INTERVAL '2893 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (29, 29, 29, CURRENT_TIMESTAMP - INTERVAL '2990 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (30, 30, 30, CURRENT_TIMESTAMP - INTERVAL '3087 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (31, 31, 31, CURRENT_TIMESTAMP - INTERVAL '3184 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (32, 32, 32, CURRENT_TIMESTAMP - INTERVAL '3281 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (33, 33, 33, CURRENT_TIMESTAMP - INTERVAL '3378 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (34, 34, 34, CURRENT_TIMESTAMP - INTERVAL '3475 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (35, 35, 35, CURRENT_TIMESTAMP - INTERVAL '3572 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (36, 36, 36, CURRENT_TIMESTAMP - INTERVAL '3669 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (37, 37, 37, CURRENT_TIMESTAMP - INTERVAL '3766 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (38, 38, 38, CURRENT_TIMESTAMP - INTERVAL '3863 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (39, 39, 39, CURRENT_TIMESTAMP - INTERVAL '3960 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (40, 40, 40, CURRENT_TIMESTAMP - INTERVAL '4057 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (41, 41, 41, CURRENT_TIMESTAMP - INTERVAL '4154 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (42, 42, 42, CURRENT_TIMESTAMP - INTERVAL '4251 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (43, 43, 43, CURRENT_TIMESTAMP - INTERVAL '4348 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (44, 44, 44, CURRENT_TIMESTAMP - INTERVAL '4445 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (45, 45, 45, CURRENT_TIMESTAMP - INTERVAL '4542 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (46, 46, 46, CURRENT_TIMESTAMP - INTERVAL '4639 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (47, 47, 47, CURRENT_TIMESTAMP - INTERVAL '4736 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (48, 48, 48, CURRENT_TIMESTAMP - INTERVAL '4833 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (49, 49, 49, CURRENT_TIMESTAMP - INTERVAL '4930 minutes');
INSERT INTO NotificacaoAlerta (id_notificacao, id_alerta, id_usuario, data_hora_envio) VALUES (50, 50, 50, CURRENT_TIMESTAMP - INTERVAL '5027 minutes');